### ISSUE TITLE
Foreclosure Update 6-12-16 through 5-20-17

### ISSUE THREAD

**Issue by mcohenui** [NeighborhoodInfoDC/ROD#3]

**Comment by lhendey** [comment]
@mcohenui - we can close this issue right?

**Comment by lhendey** [comment]
@mcohenui - can you spend a few minutes reviewing whether we can close this issue? You can charge: 101597-0001-001-00001-NeighborhoodInfo DC Support 2017-18

**Comment by mcohenui** [comment]
@lhendey Yes, foreclosures were updated to 5-20-2017, and the unmatched parcel/coop files were updated. Closing now.
